version: '3.7'

services:
  learnchars:
    image: iank1/learnchars:latest
    restart: unless-stopped
    environment:
      - "SKRITTER_USERNAME=${SKRITTER_USERNAME}"
      - "SKRITTER_PW=${SKRITTER_PW}"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 24h"
      ofelia.job-exec.app.command: "/app/docker-kindle-img.sh"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    depends_on:
      - learnchars
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

